kind: Secret
apiVersion: v1
metadata:
  name: smtp-server-secret
stringData:
  url: "email-smtp.ap-northeast-1.amazonaws.com"
#  url: "52.196.38.215"
  port: "465"
  user: "AKIA22UZVNEGFO5ODQ2Q"
  password: "BDN9ZJ6aO0+HK0td8Is/H8mXbwqsbY6oy+36/EQ0aaj9"
#  tls: "False"
  tls: "True"
