apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trivy-scanner
  namespace: project2
  labels:
    app.kubernetes.io/version: '0.2'
spec:
  description: >-
    Trivy is a simple and comprehensive scanner for vulnerabilities in container
    images,file systems ,and Git repositories, as well as for configuration
    issues.

    This task can be used to scan for vulnenrabilities on the source code in
    stand alone mode.
  params:
    - description: The Arguments to be passed to Trivy command.
      name: ARGS
      type: array
    - default: 'docker.io/aquasec/trivy:0.38.3'
      description: Trivy scanner image to be used
      name: TRIVY_IMAGE
      type: string
    - description: Image or Path to be scanned by trivy.
      name: IMAGE_PATH
      type: string
    - default: 'false'
      description: a flag enabling Air-Gapped mode
      name: AIR_GAPPED_ENABLED
      type: string
  results:
    - name: log
    - name: status
  steps:
    - args:
        - $(params.ARGS)
      image: $(params.TRIVY_IMAGE)
      name: trivy-scan
      resources: {}
      script: |
        #!/usr/bin/env sh
          cmd="trivy --quiet $* "
          if [ "$(params.AIR_GAPPED_ENABLED)" = "true" ]; then
            echo "Air-Gapped mode enabled"
            TRIVY_TEMP_DIR=$(mktemp -d)
            trivy --cache-dir $TRIVY_TEMP_DIR image --download-db-only
            tar -cf ./db.tar.gz -C $TRIVY_TEMP_DIR/db metadata.json trivy.db
            rm -rf $TRIVY_TEMP_DIR
            mkdir -p $HOME/.cache/trivy/db
            tar xvf ./db.tar.gz -C $HOME/.cache/trivy/db
            cmd="$cmd --skip-update "
          fi
          cmd="$cmd $(params.IMAGE_PATH)"
          echo "Running trivy task with command below"
          echo "$cmd"
          set -o pipefail
          $cmd | tee $(results.log.path)
          if [ $? -ne 0 ]; then
            echo -n "Failed" > $(results.status.path)
          else
            echo -n "Success" > $(results.status.path)
          fi
      workingDir: $(workspaces.manifest-dir.path)
  workspaces:
    - name: manifest-dir
